version: 2
jobs:
  test-node:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: "yarn install"
      - run: "yarn lint:ci"
      - run: "yarn build"
      - run: "mkdir -p tmp/artifacts"
      - run: "yarn test:node -- --maxWorkers=4 --json --outputFile=tmp/artifacts/test-output.json"
      - run: 
          command: "./scripts/pr-parser-preview.sh"
          when: "always"

      - store_artifacts:
          path: tmp/artifacts

  test-web:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: "yarn install"
      # For some reason phantomjs-prebuild is failing w/yarn, but npm installing works
      - run: "npm install phantomjs-prebuilt"
      # Switch to 7 and lint
      - run: "yarn test:web -- --maxWorkers=4"
      - run: "yarn build:web -- --maxWorkers=4"

  update-fixtures:
    docker:
      - image: circleci/node:6.14-stretch
    steps:
      - checkout
      - run: "yarn install"
      - run: "node ./scripts/update-fixtures.js"


workflows:
  version: 2
  build_and_test:
    jobs:
      - test-node
      - test-web
  # UNCOMMENT WHEN READY TO AUTOMATE THIS TASK
  # scheduled_tasks:
  #   triggers:
  #     # run once per hour
  #     - schedule:
  #       cron: "0 * * * *"
  #       filters:
  #         branches:
  #           only:
  #             - master
  #   jobs:
  #     - update-fixtures
